### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by niyezaimengli** [emilamaj/bookwriter#4]
我想知道如何使用这个app，怎么安装它呢

**Comment by emilamaj** [comment]
Hello,
Right now to use this app, you need to have a software development setup on your machine. Have you tried downloading the repository and running the commands suggested in readme.md ?

**Comment by niyezaimengli** [comment]
> Hello, Right now to use this app, you need to have a software development setup on your machine. Have you tried downloading the repository and running the commands suggested in readme.md ?

sorry,I tried to read it before, but maybe I didn't read it very carefully, I will pay attention next time.thank for your reply!!
